# Generated by Django 4.2.6 on 2023-11-12 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appentrega3', '0007_contacto_delete_personal_delete_profesor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('dni', models.IntegerField()),
            ],
        ),
    ]
