# Generated by Django 4.2.6 on 2023-11-12 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appentrega3', '0008_pedido'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Curso',
        ),
        migrations.DeleteModel(
            name='Estudiante',
        ),
    ]
