# Generated by Django 4.2.6 on 2023-11-18 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appentrega3', '0010_agregarpedido'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agregarpedido',
            old_name='pedido',
            new_name='detallar',
        ),
    ]
